<?xml version="1.0" encoding="utf-8"?>
<TestRun id="1ca2f5c5-3e2b-4f7e-a565-c63d2f0b9758" name="anna@cloudtest-win10 2023-01-24 01:54:29" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-24T01:54:29.3120915+00:00" queuing="2023-01-24T01:54:29.3120920+00:00" start="2023-01-24T01:54:21.3991714+00:00" finish="2023-01-24T01:54:29.3523866+00:00" />
  <TestSettings name="default" id="15fb8519-016d-4c7b-8ca9-16f8c096004c">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-24_01_54_29" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="fc66be7c-0b46-4b8a-a401-d66af804b6da" testId="6027bfe0-b63c-1dea-6056-192796d084f9" testName="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_UnregisterSiloInstance" computerName="cloudtest-win10" duration="00:00:03.1015906" startTime="2023-01-24T01:54:29.0133375+00:00" endTime="2023-01-24T01:54:29.0133814+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="fc66be7c-0b46-4b8a-a401-d66af804b6da">
      <Output>
        <StdOut>ClusterId=test-e81641a1-60da-4aab-8152-4f5589f0b9f4 Generation=33530065&#xD;
Initializing SiloInstanceManager&#xD;
MyEntry=OrleansSilo [ Deployment=test-e81641a1-60da-4aab-8152-4f5589f0b9f4 LocalEndpoint=127.0.0.1 LocalPort=0 Generation=33530065 Host=127.0.0.1 Status= ProxyPort=30000 RoleName=MyRole SiloName=MyInstance UpgradeZone=0 FaultZone=0 StartTime=2023-01-24 01:54:26.679 GMT IAmAliveTime=]&#xD;
TestCleanup Timeout=00:01:00</StdOut>
        <ErrorInfo>
          <Message>System.AggregateException : One or more errors occurred. (The specified resource does not exist.
RequestId:0d01832f-0002-000a-7496-2fefb0000000
Time:2023-01-24T01:54:28.9823611Z&#xD;
Status: 404 (Not Found)&#xD;
ErrorCode: ResourceNotFound&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:0d01832f-0002-000a-7496-2fefb0000000\nTime:2023-01-24T01:54:28.9823611Z"}}}&#xD;
&#xD;
Headers:&#xD;
X-Content-Type-Options: REDACTED&#xD;
Cache-Control: no-cache&#xD;
DataServiceVersion: 3.0;&#xD;
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
)&#xD;
---- Azure.Data.Tables.TableTransactionFailedException : The specified resource does not exist.
RequestId:0d01832f-0002-000a-7496-2fefb0000000
Time:2023-01-24T01:54:28.9823611Z&#xD;
Status: 404 (Not Found)&#xD;
ErrorCode: ResourceNotFound&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:0d01832f-0002-000a-7496-2fefb0000000\nTime:2023-01-24T01:54:28.9823611Z"}}}&#xD;
&#xD;
Headers:&#xD;
X-Content-Type-Options: REDACTED&#xD;
Cache-Control: no-cache&#xD;
DataServiceVersion: 3.0;&#xD;
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
</Message>
          <StackTrace>   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#xD;
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#xD;
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)&#xD;
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)&#xD;
   at Orleans.Internal.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout) in C:\Users\anna\orleans\src\Orleans.Core\Async\TaskExtensions.cs:line 49&#xD;
   at Tester.AzureUtils.SiloInstanceTableManagerTests.Dispose() in C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\SiloInstanceTableManagerTests.cs:line 70&#xD;
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs:line 79&#xD;
----- Inner Stack Trace -----&#xD;
   at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)&#xD;
   at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.DeleteTableEntriesAsync(List`1 collection) in C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs:line 483&#xD;
   at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteEntriesBatch(List`1 entriesList) in C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs:line 197&#xD;
   at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteTableEntries(String clusterId) in C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs:line 177</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_UnregisterSiloInstance" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="6027bfe0-b63c-1dea-6056-192796d084f9">
      <Execution id="fc66be7c-0b46-4b8a-a401-d66af804b6da" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.SiloInstanceTableManagerTests" name="SiloInstanceTable_Op_UnregisterSiloInstance" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="6027bfe0-b63c-1dea-6056-192796d084f9" executionId="fc66be7c-0b46-4b8a-a401-d66af804b6da" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.25]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.46]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.48]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:04.68]       System.AggregateException : One or more errors occurred. (The specified resource does not exist.
RequestId:0d01832f-0002-000a-7496-2fefb0000000
Time:2023-01-24T01:54:28.9823611Z&#xD;
[xUnit.net 00:00:04.68]       Status: 404 (Not Found)&#xD;
[xUnit.net 00:00:04.68]       ErrorCode: ResourceNotFound&#xD;
[xUnit.net 00:00:04.68]       &#xD;
[xUnit.net 00:00:04.68]       Content:&#xD;
[xUnit.net 00:00:04.68]       {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:0d01832f-0002-000a-7496-2fefb0000000\nTime:2023-01-24T01:54:28.9823611Z"}}}&#xD;
[xUnit.net 00:00:04.68]       &#xD;
[xUnit.net 00:00:04.68]       Headers:&#xD;
[xUnit.net 00:00:04.68]       X-Content-Type-Options: REDACTED&#xD;
[xUnit.net 00:00:04.68]       Cache-Control: no-cache&#xD;
[xUnit.net 00:00:04.68]       DataServiceVersion: 3.0;&#xD;
[xUnit.net 00:00:04.68]       Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
[xUnit.net 00:00:04.68]       )&#xD;
[xUnit.net 00:00:04.68]       ---- Azure.Data.Tables.TableTransactionFailedException : The specified resource does not exist.
RequestId:0d01832f-0002-000a-7496-2fefb0000000
Time:2023-01-24T01:54:28.9823611Z&#xD;
[xUnit.net 00:00:04.68]       Status: 404 (Not Found)&#xD;
[xUnit.net 00:00:04.68]       ErrorCode: ResourceNotFound&#xD;
[xUnit.net 00:00:04.68]       &#xD;
[xUnit.net 00:00:04.68]       Content:&#xD;
[xUnit.net 00:00:04.68]       {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:0d01832f-0002-000a-7496-2fefb0000000\nTime:2023-01-24T01:54:28.9823611Z"}}}&#xD;
[xUnit.net 00:00:04.68]       &#xD;
[xUnit.net 00:00:04.68]       Headers:&#xD;
[xUnit.net 00:00:04.68]       X-Content-Type-Options: REDACTED&#xD;
[xUnit.net 00:00:04.68]       Cache-Control: no-cache&#xD;
[xUnit.net 00:00:04.68]       DataServiceVersion: 3.0;&#xD;
[xUnit.net 00:00:04.68]       Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
[xUnit.net 00:00:04.68]       &#xD;
[xUnit.net 00:00:04.68]       Stack Trace:&#xD;
[xUnit.net 00:00:04.68]            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#xD;
[xUnit.net 00:00:04.68]            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:04.68]            at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:04.68]            at System.Threading.Tasks.Task.Wait(TimeSpan timeout)&#xD;
[xUnit.net 00:00:04.68]         C:\Users\anna\orleans\src\Orleans.Core\Async\TaskExtensions.cs(49,0): at Orleans.Internal.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)&#xD;
[xUnit.net 00:00:04.68]         C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\SiloInstanceTableManagerTests.cs(70,0): at Tester.AzureUtils.SiloInstanceTableManagerTests.Dispose()&#xD;
[xUnit.net 00:00:04.68]         /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs(79,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)&#xD;
[xUnit.net 00:00:04.68]         ----- Inner Stack Trace -----&#xD;
[xUnit.net 00:00:04.68]            at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:04.68]            at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:04.68]            at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:04.68]         C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs(483,0): at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.DeleteTableEntriesAsync(List`1 collection)&#xD;
[xUnit.net 00:00:04.68]         C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs(197,0): at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteEntriesBatch(List`1 entriesList)&#xD;
[xUnit.net 00:00:04.68]         C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs(177,0): at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteTableEntries(String clusterId)&#xD;
[xUnit.net 00:00:04.68]       Output:&#xD;
[xUnit.net 00:00:04.68]         ClusterId=test-e81641a1-60da-4aab-8152-4f5589f0b9f4 Generation=33530065&#xD;
[xUnit.net 00:00:04.68]         Initializing SiloInstanceManager&#xD;
[xUnit.net 00:00:04.68]         MyEntry=OrleansSilo [ Deployment=test-e81641a1-60da-4aab-8152-4f5589f0b9f4 LocalEndpoint=127.0.0.1 LocalPort=0 Generation=33530065 Host=127.0.0.1 Status= ProxyPort=30000 RoleName=MyRole SiloName=MyInstance UpgradeZone=0 FaultZone=0 StartTime=2023-01-24 01:54:26.679 GMT IAmAliveTime=]&#xD;
[xUnit.net 00:00:04.68]         TestCleanup Timeout=00:01:00&#xD;
[xUnit.net 00:00:04.72]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-24T01:54:29.0062268+00:00">
        <Text>[xUnit.net 00:00:04.68]     Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_UnregisterSiloInstance [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-24T01:54:29.1661490+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>