METHOD: dynamo_batch_execute_statement --- ARGS: 
AWS : Success -- Batch execute statement succeeded
EMULATOR : Success -- Batch execute statement succeeded
Exception:  'str' object has no attribute 'response'
AWS : Success -- Table deleted
AWS : Success -- Table deleted
AWS : Success -- Table deleted
AWS : Success -- Table deleted
AWS : Success -- Table deleted
AWS : Success -- Table deleted
AWS : Success -- Table deleted
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table32528171
EMULATOR : Success -- Table deleted
METHOD: dynamo_batch_get_item --- ARGS: 
AWS : Fail -- Batch get item failed; error:  An error occurred (ResourceNotFoundException) when calling the BatchGetItem operation: Requested resource not found
EMULATOR : Success -- Batch get item succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the BatchGetItem operation: Requested resource not found 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being deleted: table245955693
EMULATOR : Success -- Table deleted
METHOD: dynamo_batch_write_item --- ARGS: 
AWS : Fail -- Batch write item failed; error:  An error occurred (ResourceNotFoundException) when calling the BatchWriteItem operation: Requested resource not found
EMULATOR : Success -- Batch write item succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the BatchWriteItem operation: Requested resource not found 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being deleted: table245955693
EMULATOR : Success -- Table deleted
METHOD: dynamo_can_paginate --- ARGS: 
AWS : Success -- Can paginate succeeded
EMULATOR : Success -- Can paginate succeeded
Exception:  'str' object has no attribute 'response'
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being deleted: table295948162
EMULATOR : Success -- Table deleted
METHOD: dynamo_create_backup --- ARGS: 
AWS : Fail -- Create backup failed; error:  An error occurred (TableNotFoundException) when calling the CreateBackup operation: Table not found: table720724559
EMULATOR : Fail -- Create backup failed; error:  An error occurred (UnknownOperationException) when calling the CreateBackup operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Table not found: table720724559 -- Error Code: TableNotFoundException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table32528171
EMULATOR : Success -- Table deleted
METHOD: dynamo_create_global_table --- ARGS: 
AWS : Fail -- Create global table failed; error:  An error occurred (TableNotFoundException) when calling the CreateGlobalTable operation: Table not found: Table: 'table704465447' not found in region: 'us-east-1'.
EMULATOR : Success -- Create global table succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (TableNotFoundException) when calling the CreateGlobalTable operation: Table not found: Table: 'table704465447' not found in region: 'us-east-1'. 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table32528171
EMULATOR : Success -- Table deleted
METHOD: dynamo_create_table --- ARGS: 
AWS : Success -- Table created
EMULATOR : Success -- Table created
Exception:  'str' object has no attribute 'response'
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table32528171
EMULATOR : Success -- Table deleted
EMULATOR : Success -- Table deleted
METHOD: dynamo_delete_backup --- ARGS: 
AWS : Fail -- Delete backup failed; error:  An error occurred (ValidationException) when calling the DeleteBackup operation: Invalid Request: BackupArn is not valid
EMULATOR : Fail -- Delete backup failed; error:  An error occurred (UnknownOperationException) when calling the DeleteBackup operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Invalid Request: BackupArn is not valid -- Error Code: ValidationException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table142999429
EMULATOR : Success -- Table deleted
METHOD: dynamo_delete_item --- ARGS: 
AWS : Fail -- Delete item failed; error:  An error occurred (ResourceNotFoundException) when calling the DeleteItem operation: Requested resource not found
EMULATOR : Success -- Delete item succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the DeleteItem operation: Requested resource not found 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table113923409
EMULATOR : Success -- Table deleted
METHOD: dynamo_delete_table --- ARGS: 
AWS : Fail -- Delete table failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table270294511
EMULATOR : Success -- Delete table succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table270294511 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table113923409
METHOD: dynamo_describe_backup --- ARGS: 
AWS : Fail -- Describe backup failed; error:  An error occurred (ValidationException) when calling the DescribeBackup operation: Invalid Request: BackupArn is not valid
EMULATOR : Fail -- Describe backup failed; error:  An error occurred (UnknownOperationException) when calling the DescribeBackup operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Invalid Request: BackupArn is not valid -- Error Code: ValidationException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table113923409
EMULATOR : Success -- Table deleted
METHOD: dynamo_describe_continuous_backups --- ARGS: 
AWS : Fail -- Describe continuous backups failed; error:  An error occurred (TableNotFoundException) when calling the DescribeContinuousBackups operation: Table not found: table721716302
EMULATOR : Success -- Describe continuous backups succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (TableNotFoundException) when calling the DescribeContinuousBackups operation: Table not found: table721716302 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table113923409
EMULATOR : Success -- Table deleted
METHOD: dynamo_describe_global_table --- ARGS: 
AWS : Fail -- Describe global table failed; error:  An error occurred (GlobalTableNotFoundException) when calling the DescribeGlobalTable operation: Global table not found: Global table with name: 'table925766842' does not exist.
EMULATOR : Fail -- Describe global table failed; error:  An error occurred (GlobalTableNotFoundException) when calling the DescribeGlobalTable operation: Global table with this name does not exist

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Global table not found: Global table with name: 'table925766842' does not exist. -- Error Code: GlobalTableNotFoundException
EMULATOR: FAILURE -- Error Message: Global table with this name does not exist -- Error Code: GlobalTableNotFoundException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table113923409
EMULATOR : Success -- Table deleted
METHOD: dynamo_describe_global_table_settings --- ARGS: 
AWS : Fail -- Describe global table settings failed; error:  An error occurred (GlobalTableNotFoundException) when calling the DescribeGlobalTableSettings operation: Global table with name: 'table586322193' does not exist.
EMULATOR : Fail -- Describe global table settings failed; error:  An error occurred (UnknownOperationException) when calling the DescribeGlobalTableSettings operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Global table with name: 'table586322193' does not exist. -- Error Code: GlobalTableNotFoundException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table113923409
EMULATOR : Success -- Table deleted
METHOD: dynamo_describe_import --- ARGS: 
AWS : Fail -- Describe import failed; error:  An error occurred (ValidationException) when calling the DescribeImport operation: Invalid Import ARN
EMULATOR : Fail -- Describe import failed; error:  An error occurred (UnknownOperationException) when calling the DescribeImport operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Invalid Import ARN -- Error Code: ValidationException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table113923409
EMULATOR : Success -- Table deleted
METHOD: dynamo_describe_kinesis_streaming_destination --- ARGS: 
AWS : Fail -- Describe kinesis streaming destination failed; error:  An error occurred (ResourceNotFoundException) when calling the DescribeKinesisStreamingDestination operation: Requested resource not found: Table: table357222825 not found
EMULATOR : Success -- Describe kinesis streaming destination succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the DescribeKinesisStreamingDestination operation: Requested resource not found: Table: table357222825 not found 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table113923409
EMULATOR : Success -- Table deleted
METHOD: dynamo_describe_limits --- ARGS: 
AWS : Success -- Describe limits succeeded
EMULATOR : Success -- Describe limits succeeded
Exception:  'str' object has no attribute 'response'
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table113923409
EMULATOR : Success -- Table deleted
METHOD: dynamo_describe_table --- ARGS: 
AWS : Success -- Describe table succeeded
EMULATOR : Success -- Describe table succeeded
Exception:  'str' object has no attribute 'response'
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table113923409
EMULATOR : Success -- Table deleted
METHOD: dynamo_describe_table_replication_auto_scaling --- ARGS: 
AWS : Fail -- Describe table replication auto scaling failed; error:  An error occurred (ResourceNotFoundException) when calling the DescribeTableReplicaAutoScaling operation: Global table with name: 'table28382122' does not exist.
EMULATOR : Fail -- Describe table replication auto scaling failed; error:  An error occurred (UnknownOperationException) when calling the DescribeTableReplicaAutoScaling operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Global table with name: 'table28382122' does not exist. -- Error Code: ResourceNotFoundException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Success -- Table deleted
AWS : Success -- Table deleted
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table270294511
EMULATOR : Success -- Table deleted
METHOD: dynamo_describe_time_to_live --- ARGS: 
AWS : Fail -- Describe time to live failed; error:  An error occurred (ValidationException) when calling the DescribeTimeToLive operation: Cannot describe time to live while table is in CREATING state: Current table state is CREATING
EMULATOR : Success -- Describe time to live succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ValidationException) when calling the DescribeTimeToLive operation: Cannot describe time to live while table is in CREATING state: Current table state is CREATING 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being deleted: table113923409
EMULATOR : Success -- Table deleted
METHOD: dynamo_execute_statement --- ARGS: 
AWS : Fail -- Execute statement failed; error:  An error occurred (ResourceNotFoundException) when calling the ExecuteStatement operation: Requested resource not found
EMULATOR : Success -- Execute statement succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the ExecuteStatement operation: Requested resource not found 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being deleted: table113923409
EMULATOR : Success -- Table deleted
METHOD: dynamo_execute_transaction --- ARGS: 
AWS : Fail -- Execute transaction failed; error:  An error occurred (ValidationException) when calling the ExecuteTransaction operation: Supplied AttributeValue has more than one datatypes set, must contain exactly one of the supported datatypes
EMULATOR : Fail -- Execute transaction failed; error:  An error occurred (ValidationException) when calling the ExecuteTransaction operation: Supplied AttributeValue has more than one datatypes set, must contain exactly one of the supported datatypes
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being deleted: table113923409
EMULATOR : Success -- Table deleted
METHOD: dynamo_export_table_to_point_in_time --- ARGS: 
AWS : Fail -- Export table to point in time failed; error:  An error occurred (ValidationException) when calling the ExportTableToPointInTime operation: One or more parameter values were invalid: tableArn is not a valid ARN
EMULATOR : Fail -- Export table to point in time failed; error:  An error occurred (UnknownOperationException) when calling the ExportTableToPointInTime operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: One or more parameter values were invalid: tableArn is not a valid ARN -- Error Code: ValidationException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_get_item --- ARGS: 
AWS : Fail -- Get item failed; error:  An error occurred (ResourceNotFoundException) when calling the GetItem operation: Requested resource not found
EMULATOR : Success -- Get item succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the GetItem operation: Requested resource not found 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_get_paginator --- ARGS: 
AWS : Fail -- Get paginator failed; error:  'ListTables'
EMULATOR : Fail -- Get paginator failed; error:  'ListTables'
Exception:  'KeyError' object has no attribute 'response'
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_get_waiter --- ARGS: 
AWS : Fail -- Get waiter failed; error:  Waiter does not exist: TableExists
EMULATOR : Fail -- Get waiter failed; error:  Waiter does not exist: TableExists
Exception:  'ValueError' object has no attribute 'response'
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_import_table --- ARGS: 
AWS : Fail -- Import table failed; error:  An error occurred (ValidationException) when calling the ImportTable operation: One or more parameter values were invalid: ReadCapacityUnits and WriteCapacityUnits must both be specified when BillingMode is PROVISIONED
EMULATOR : Fail -- Import table failed; error:  An error occurred (UnknownOperationException) when calling the ImportTable operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: One or more parameter values were invalid: ReadCapacityUnits and WriteCapacityUnits must both be specified when BillingMode is PROVISIONED -- Error Code: ValidationException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_list_backups --- ARGS: 
AWS : Success -- List backups succeeded
EMULATOR : Fail -- List backups failed; error:  An error occurred (UnknownOperationException) when calling the ListBackups operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: SUCCESS -- Response:  
EMULATOR: FAILURE -- Response: An error occurred (UnknownOperationException) when calling the ListBackups operation: An unknown operation was requested.


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_list_contributor_insights --- ARGS: 
AWS : Fail -- List contributor insights failed; error:  An error occurred (ResourceNotFoundException) when calling the ListContributorInsights operation: Requested resource not found: Table: table851528683 not found
EMULATOR : Fail -- List contributor insights failed; error:  An error occurred (UnknownOperationException) when calling the ListContributorInsights operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Requested resource not found: Table: table851528683 not found -- Error Code: ResourceNotFoundException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_list_exports --- ARGS: 
AWS : Fail -- List exports failed; error:  An error occurred (ValidationException) when calling the ListExports operation: One or more parameter values were invalid: tableArn is not a valid ARN
EMULATOR : Fail -- List exports failed; error:  An error occurred (UnknownOperationException) when calling the ListExports operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: One or more parameter values were invalid: tableArn is not a valid ARN -- Error Code: ValidationException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_list_global_tables --- ARGS: 
AWS : Success -- List global tables succeeded
EMULATOR : Success -- List global tables succeeded
Exception:  'str' object has no attribute 'response'
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_list_imports --- ARGS: 
AWS : Success -- List imports succeeded
EMULATOR : Fail -- List imports failed; error:  An error occurred (UnknownOperationException) when calling the ListImports operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: SUCCESS -- Response:  
EMULATOR: FAILURE -- Response: An error occurred (UnknownOperationException) when calling the ListImports operation: An unknown operation was requested.


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_list_tables --- ARGS: 
AWS : Success -- List tables succeeded
EMULATOR : Success -- List tables succeeded
Exception:  'str' object has no attribute 'response'
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_list_tags_of_resource --- ARGS: 
AWS : Fail -- List tags of resource failed; error:  An error occurred (ValidationException) when calling the ListTagsOfResource operation: Invalid TableArn: Invalid ResourceArn provided as input arn:aws:dynamodb:us-east-1:123456789012:table/table549668007
EMULATOR : Success -- List tags of resource succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ValidationException) when calling the ListTagsOfResource operation: Invalid TableArn: Invalid ResourceArn provided as input arn:aws:dynamodb:us-east-1:123456789012:table/table549668007 
EMULATOR: SUCCESS -- Response: 


AWS : Success -- Table deleted
AWS : Success -- Table deleted
AWS : Success -- Table deleted
AWS : Success -- Table deleted
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table28382122
EMULATOR : Success -- Table deleted
METHOD: dynamo_put_item --- ARGS: 
AWS : Fail -- Item put failed; error:  An error occurred (ValidationException) when calling the PutItem operation: Supplied AttributeValue is empty, must contain exactly one of the supported datatypes
EMULATOR : Fail -- Item put failed; error:  An error occurred (ValidationException) when calling the PutItem operation: Supplied AttributeValue is empty, must contain exactly one of the supported datatypes
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being deleted: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_restore_table_from_backup --- ARGS: 
AWS : Fail -- Restore table from backup failed; error:  An error occurred (ValidationException) when calling the RestoreTableFromBackup operation: Invalid Backup ARN
EMULATOR : Fail -- Restore table from backup failed; error:  An error occurred (UnknownOperationException) when calling the RestoreTableFromBackup operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Invalid Backup ARN -- Error Code: ValidationException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being deleted: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_restore_table_to_point_in_time --- ARGS: 
AWS : Fail -- Restore table to point in time failed; error:  An error occurred (ValidationException) when calling the RestoreTableToPointInTime operation: Invalid Request: Both RestoreDateTime and UseLatestRestorableTime cannot be set for point-in-time restore request. Please specify either RestoreDateTime time or UseLatestRestorableTime
EMULATOR : Fail -- Restore table to point in time failed; error:  An error occurred (UnknownOperationException) when calling the RestoreTableToPointInTime operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Invalid Request: Both RestoreDateTime and UseLatestRestorableTime cannot be set for point-in-time restore request. Please specify either RestoreDateTime time or UseLatestRestorableTime -- Error Code: ValidationException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being deleted: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_scan --- ARGS: 
AWS : Fail -- Scan failed; error:  An error occurred (ValidationException) when calling the Scan operation: ExpressionAttributeValues contains invalid value: Supplied AttributeValue is empty, must contain exactly one of the supported datatypes for key :val
EMULATOR : Fail -- Scan failed; error:  An error occurred (ValidationException) when calling the Scan operation: ExpressionAttributeValues contains invalid value: Supplied AttributeValue is empty, must contain exactly one of the supported datatypes for key :val
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being deleted: table191962023
EMULATOR : Success -- Table deleted
METHOD: dynamo_tag_resource --- ARGS: 
AWS : Fail -- Tag resource failed; error:  An error occurred (ValidationException) when calling the TagResource operation: Invalid TableArn: Invalid ResourceArn provided as input arn:aws:dynamodb:us-east-1:123456789012:table/table613706445
EMULATOR : Success -- Tag resource succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ValidationException) when calling the TagResource operation: Invalid TableArn: Invalid ResourceArn provided as input arn:aws:dynamodb:us-east-1:123456789012:table/table613706445 
EMULATOR: SUCCESS -- Response: 


AWS : Success -- Table deleted
AWS : Success -- Table deleted
AWS : Success -- Table deleted
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table329996163
EMULATOR : Success -- Table deleted
METHOD: dynamo_transact_get_items --- ARGS: 
AWS : Fail -- Transact get items failed; error:  An error occurred (ValidationException) when calling the TransactGetItems operation: ExpressionAttributeNames contains invalid key: Syntax error; key: "string"
EMULATOR : Fail -- Transact get items failed; error:  An error occurred (ValidationException) when calling the TransactGetItems operation: ExpressionAttributeNames contains invalid key: Syntax error; key: "string"
AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being deleted: table28382122
EMULATOR : Success -- Table deleted
METHOD: dynamo_transact_write_items --- ARGS: 
AWS : Fail -- Transact write items failed; error:  An error occurred (ValidationException) when calling the TransactWriteItems operation: ExpressionAttributeNames contains invalid key: Syntax error; key: "string"
EMULATOR : Fail -- Transact write items failed; error:  An error occurred (ValidationException) when calling the TransactWriteItems operation: The provided key element does not match the schema

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: ExpressionAttributeNames contains invalid key: Syntax error; key: "string" -- Error Code: ValidationException
EMULATOR: FAILURE -- Error Message: The provided key element does not match the schema -- Error Code: ValidationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being deleted: table28382122
EMULATOR : Success -- Table deleted
METHOD: dynamo_untag_resource --- ARGS: 
AWS : Fail -- Untag resource failed; error:  An error occurred (ValidationException) when calling the UntagResource operation: Invalid TableArn: Invalid ResourceArn provided as input arn:aws:dynamodb:us-east-1:123456789012:table/table346647684
EMULATOR : Success -- Untag resource succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ValidationException) when calling the UntagResource operation: Invalid TableArn: Invalid ResourceArn provided as input arn:aws:dynamodb:us-east-1:123456789012:table/table346647684 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceNotFoundException) when calling the DeleteTable operation: Requested resource not found: Table: table28382122 not found
EMULATOR : Success -- Table deleted
METHOD: dynamo_update_continuous_backups --- ARGS: 
AWS : Fail -- Update continuous backups failed; error:  An error occurred (TableNotFoundException) when calling the UpdateContinuousBackups operation: Table not found: table984189666
EMULATOR : Success -- Update continuous backups succeeded

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (TableNotFoundException) when calling the UpdateContinuousBackups operation: Table not found: table984189666 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table313702840
EMULATOR : Success -- Table deleted
METHOD: dynamo_update_contributor_insights --- ARGS: 
AWS : Fail -- Update contributor insights failed; error:  An error occurred (ResourceNotFoundException) when calling the UpdateContributorInsights operation: Requested resource not found: Table: table681424693 not found
EMULATOR : Fail -- Update contributor insights failed; error:  An error occurred (UnknownOperationException) when calling the UpdateContributorInsights operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Requested resource not found: Table: table681424693 not found -- Error Code: ResourceNotFoundException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table313702840
EMULATOR : Success -- Table deleted
METHOD: dynamo_update_global_table --- ARGS: 
AWS : Fail -- Update global table failed; error:  An error occurred (GlobalTableNotFoundException) when calling the UpdateGlobalTable operation: Global table not found: Global table with name: 'table974677673' does not exist.
EMULATOR : Fail -- Update global table failed; error:  An error occurred (GlobalTableNotFoundException) when calling the UpdateGlobalTable operation: Global table with this name does not exist

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Global table not found: Global table with name: 'table974677673' does not exist. -- Error Code: GlobalTableNotFoundException
EMULATOR: FAILURE -- Error Message: Global table with this name does not exist -- Error Code: GlobalTableNotFoundException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table313702840
EMULATOR : Success -- Table deleted
METHOD: dynamo_update_global_table_settings --- ARGS: 
AWS : Fail -- Update global table settings failed; error:  An error occurred (ValidationException) when calling the UpdateGlobalTableSettings operation: One or more parameter values were invalid: Failed to update settings for global table with name ‘table643094398’: Parameters 'MaximumUnits', 'ScalingPolicyUpdate', 'MinimumUnits' must be left blank when disabling auto scaling.
EMULATOR : Fail -- Update global table settings failed; error:  An error occurred (UnknownOperationException) when calling the UpdateGlobalTableSettings operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: One or more parameter values were invalid: Failed to update settings for global table with name ‘table643094398’: Parameters 'MaximumUnits', 'ScalingPolicyUpdate', 'MinimumUnits' must be left blank when disabling auto scaling. -- Error Code: ValidationException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table313702840
EMULATOR : Success -- Table deleted
METHOD: dynamo_update_item --- ARGS: 
AWS : Fail -- Item update failed; error:  An error occurred (ResourceNotFoundException) when calling the UpdateItem operation: Requested resource not found
EMULATOR : Success -- Item updated

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the UpdateItem operation: Requested resource not found 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table313702840
EMULATOR : Success -- Table deleted
METHOD: dynamo_update_replica_autoscaling --- ARGS: 
AWS : Fail -- Replica autoscaling update failed; error:  An error occurred (ValidationException) when calling the UpdateTableReplicaAutoScaling operation: Failed to update settings for global table with name: ‘table348909248’: Parameters 'MaximumUnits', 'MinimumUnits' are required unless auto scaling is being disabled.
EMULATOR : Fail -- Replica autoscaling update failed; error:  An error occurred (UnknownOperationException) when calling the UpdateTableReplicaAutoScaling operation: An unknown operation was requested.

DISCREPANCY FOUND!

--Error message mismatch--
CLOUD: FAILURE  -- Error Message: Failed to update settings for global table with name: ‘table348909248’: Parameters 'MaximumUnits', 'MinimumUnits' are required unless auto scaling is being disabled. -- Error Code: ValidationException
EMULATOR: FAILURE -- Error Message: An unknown operation was requested. -- Error Code: UnknownOperationException


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table313702840
EMULATOR : Success -- Table deleted
METHOD: dynamo_update_table --- ARGS: 
AWS : Fail -- Table update failed; error:  An error occurred (ResourceInUseException) when calling the UpdateTable operation: Attempt to change a resource which is still in use: Table is being created: table821797905
EMULATOR : Success -- Table updated

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceInUseException) when calling the UpdateTable operation: Attempt to change a resource which is still in use: Table is being created: table821797905 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table313702840
EMULATOR : Success -- Table deleted
METHOD: dynamo_update_ttl --- ARGS: 
AWS : Fail -- TTL update failed; error:  An error occurred (ResourceNotFoundException) when calling the UpdateTimeToLive operation: Requested resource not found: Table: table102057891 not found
EMULATOR : Success -- TTL updated

DISCREPANCY FOUND!

--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the UpdateTimeToLive operation: Requested resource not found: Table: table102057891 not found 
EMULATOR: SUCCESS -- Response: 


AWS : Fail -- Table delete failed; error:  An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table102057891
EMULATOR : Success -- Table deleted