0/50   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Round ended

DISCREPANT METHOD: dynamo_batch_get_item --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the BatchGetItem operation: Requested resource not found 
EMULATOR: SUCCESS -- Response: 


count: 1   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_batch_write_item --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the BatchWriteItem operation: Requested resource not found 
EMULATOR: SUCCESS -- Response: 


count: 2   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_create_global_table --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (TableNotFoundException) when calling the CreateGlobalTable operation: Table not found: Table: 'table555595923' not found in region: 'us-east-1'. 
EMULATOR: SUCCESS -- Response: 


count: 3   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_delete_item --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the DeleteItem operation: Requested resource not found 
EMULATOR: SUCCESS -- Response: 


count: 4   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_delete_table --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceInUseException) when calling the DeleteTable operation: Attempt to change a resource which is still in use: Table is being created: table353602573 
EMULATOR: SUCCESS -- Response: 


count: 5   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_describe_continuous_backups --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (TableNotFoundException) when calling the DescribeContinuousBackups operation: Table not found: table229403699 
EMULATOR: SUCCESS -- Response: 


count: 6   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_describe_kinesis_streaming_destination --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the DescribeKinesisStreamingDestination operation: Requested resource not found: Table: table441197285 not found 
EMULATOR: SUCCESS -- Response: 


count: 7   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_describe_time_to_live --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ValidationException) when calling the DescribeTimeToLive operation: Cannot describe time to live while table is in CREATING state: Current table state is CREATING 
EMULATOR: SUCCESS -- Response: 


count: 8   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_execute_statement --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the ExecuteStatement operation: Requested resource not found 
EMULATOR: SUCCESS -- Response: 


count: 9   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_get_item --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the GetItem operation: Requested resource not found 
EMULATOR: SUCCESS -- Response: 


count: 10   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_list_backups --- ARGS: []
--Behavior mismatch--
CLOUD: SUCCESS -- Response:  
EMULATOR: FAILURE -- Response: An error occurred (UnknownOperationException) when calling the ListBackups operation: An unknown operation was requested.


count: 11   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_list_imports --- ARGS: []
--Behavior mismatch--
CLOUD: SUCCESS -- Response:  
EMULATOR: FAILURE -- Response: An error occurred (UnknownOperationException) when calling the ListImports operation: An unknown operation was requested.


count: 12   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_list_tags_of_resource --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ValidationException) when calling the ListTagsOfResource operation: Invalid TableArn: Invalid ResourceArn provided as input arn:aws:dynamodb:us-east-1:123456789012:table/table114156355 
EMULATOR: SUCCESS -- Response: 


count: 13   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_tag_resource --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ValidationException) when calling the TagResource operation: Invalid TableArn: Invalid ResourceArn provided as input arn:aws:dynamodb:us-east-1:123456789012:table/table321742021 
EMULATOR: SUCCESS -- Response: 


count: 14   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_untag_resource --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ValidationException) when calling the UntagResource operation: Invalid TableArn: Invalid ResourceArn provided as input arn:aws:dynamodb:us-east-1:123456789012:table/table489865478 
EMULATOR: SUCCESS -- Response: 


count: 15   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_update_continuous_backups --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (TableNotFoundException) when calling the UpdateContinuousBackups operation: Table not found: table215169763 
EMULATOR: SUCCESS -- Response: 


count: 16   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_update_item --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the UpdateItem operation: Requested resource not found 
EMULATOR: SUCCESS -- Response: 


count: 17   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_update_table --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceInUseException) when calling the UpdateTable operation: Attempt to change a resource which is still in use: Table is being created: table365303848 
EMULATOR: SUCCESS -- Response: 


count: 18   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


DISCREPANT METHOD: dynamo_update_ttl --- ARGS: []
--Behavior mismatch--
CLOUD: FAILURE -- Response: An error occurred (ResourceNotFoundException) when calling the UpdateTimeToLive operation: Requested resource not found: Table: table310989150 not found 
EMULATOR: SUCCESS -- Response: 


count: 19   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------


19/50   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Round ended

