<?xml version="1.0" encoding="utf-8"?>
<TestRun id="0153a3b1-67ca-4951-8c4b-6f5c184623e6" name="anna@cloudtest-win10 2023-01-22 19:39:37" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-22T19:39:37.4360158+00:00" queuing="2023-01-22T19:39:37.4360163+00:00" start="2023-01-22T19:39:31.6495904+00:00" finish="2023-01-22T19:39:37.4765298+00:00" />
  <TestSettings name="default" id="84d8aaf1-c10a-4119-b40f-94cd2b2f2d5c">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-22_19_39_37" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="53b835da-ff9d-422d-bfa7-6169ea3ce5f4" testId="f16aa026-a4b0-5ea6-8637-84dd3952addc" testName="Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_1" computerName="cloudtest-win10" duration="00:00:00.7984966" startTime="2023-01-22T19:39:37.1197418+00:00" endTime="2023-01-22T19:39:37.1197865+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="53b835da-ff9d-422d-bfa7-6169ea3ce5f4">
      <Output>
        <ErrorInfo>
          <Message>Assert.Equal() Failure&#xD;
Expected: 1&#xD;
Actual:   2</Message>
          <StackTrace>   at Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_1() in C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureQueueDataManagerTests.cs:line 55&#xD;
--- End of stack trace from previous location ---</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_1" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="f16aa026-a4b0-5ea6-8637-84dd3952addc">
      <Execution id="53b835da-ff9d-422d-bfa7-6169ea3ce5f4" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.AzureQueueDataManagerTests" name="AQ_Standalone_1" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="f16aa026-a4b0-5ea6-8637-84dd3952addc" executionId="53b835da-ff9d-422d-bfa7-6169ea3ce5f4" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.27]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.48]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.49]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:02.49]       Assert.Equal() Failure&#xD;
[xUnit.net 00:00:02.49]       Expected: 1&#xD;
[xUnit.net 00:00:02.49]       Actual:   2&#xD;
[xUnit.net 00:00:02.49]       Stack Trace:&#xD;
[xUnit.net 00:00:02.49]         C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureQueueDataManagerTests.cs(55,0): at Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_1()&#xD;
[xUnit.net 00:00:02.49]         --- End of stack trace from previous location ---&#xD;
[xUnit.net 00:00:02.52]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-22T19:39:37.1148188+00:00">
        <Text>[xUnit.net 00:00:02.49]     Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_1 [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-22T19:39:37.2865720+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>