<?xml version="1.0" encoding="utf-8"?>
<TestRun id="279c77b4-c420-4a5e-acc2-b7b5911a0f26" name="anna@cloudtest-win10 2023-01-24 01:53:06" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-24T01:53:06.7155615+00:00" queuing="2023-01-24T01:53:06.7155623+00:00" start="2023-01-24T01:52:59.4520553+00:00" finish="2023-01-24T01:53:06.7572410+00:00" />
  <TestSettings name="default" id="87b24eed-eeb1-4b93-ba57-e45a794b8976">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-24_01_53_06" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="ecf3b714-6a82-4744-9fe1-5a504555ea00" testId="3573d3ee-354c-3210-4087-b549fe24d804" testName="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_CreateSiloEntryConditionally" computerName="cloudtest-win10" duration="00:00:02.0134776" startTime="2023-01-24T01:53:06.4140852+00:00" endTime="2023-01-24T01:53:06.4141294+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="ecf3b714-6a82-4744-9fe1-5a504555ea00">
      <Output>
        <StdOut>ClusterId=test-bd8d1e65-706d-4fa5-9b14-e20659624764 Generation=33529984&#xD;
Initializing SiloInstanceManager&#xD;
TestCleanup Timeout=00:01:00&#xD;
TestCleanup -  Finished</StdOut>
        <ErrorInfo>
          <Message>Did insert&#xD;
Expected: True&#xD;
Actual:   False</Message>
          <StackTrace>   at Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_CreateSiloEntryConditionally() in C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\SiloInstanceTableManagerTests.cs:line 134&#xD;
--- End of stack trace from previous location ---</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_CreateSiloEntryConditionally" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="3573d3ee-354c-3210-4087-b549fe24d804">
      <Execution id="ecf3b714-6a82-4744-9fe1-5a504555ea00" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.SiloInstanceTableManagerTests" name="SiloInstanceTable_Op_CreateSiloEntryConditionally" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="3573d3ee-354c-3210-4087-b549fe24d804" executionId="ecf3b714-6a82-4744-9fe1-5a504555ea00" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.34]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.55]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.56]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:03.68]       Did insert&#xD;
[xUnit.net 00:00:03.68]       Expected: True&#xD;
[xUnit.net 00:00:03.68]       Actual:   False&#xD;
[xUnit.net 00:00:03.68]       Stack Trace:&#xD;
[xUnit.net 00:00:03.68]         C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\SiloInstanceTableManagerTests.cs(134,0): at Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_CreateSiloEntryConditionally()&#xD;
[xUnit.net 00:00:03.68]         --- End of stack trace from previous location ---&#xD;
[xUnit.net 00:00:03.68]       Output:&#xD;
[xUnit.net 00:00:03.68]         ClusterId=test-bd8d1e65-706d-4fa5-9b14-e20659624764 Generation=33529984&#xD;
[xUnit.net 00:00:03.68]         Initializing SiloInstanceManager&#xD;
[xUnit.net 00:00:03.68]         TestCleanup Timeout=00:01:00&#xD;
[xUnit.net 00:00:03.68]         TestCleanup -  Finished&#xD;
[xUnit.net 00:00:03.71]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-24T01:53:06.4084945+00:00">
        <Text>[xUnit.net 00:00:03.68]     Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_CreateSiloEntryConditionally [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-24T01:53:06.5703902+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>