Logs for test: Can_cache_multiple_items_in_parallel


     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 2.2.0

[01:31:49] starting LocalStack in Docker mode 🐳                                                                                                           localstack.py:409
────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ───────────────────────────────────────────────────────────────

LocalStack version: 2.2.1.dev
LocalStack Docker container id: c72987487236
LocalStack build date: 2023-09-07
LocalStack build git hash: 5473e686

2024-03-01T20:31:50.872  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2024-03-01T20:31:50.872  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
Ready.
2024-03-01T20:31:53.756  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "require" took 1404.02ms
2024-03-01T20:31:53.890  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.DescribeTable => 400 (ResourceNotFoundException)
2024-03-01T20:31:53.941  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.ListTables => 200
2024-03-01T20:31:54.024  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.CreateTable => 200
2024-03-01T20:31:54.043  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.DescribeTable => 200
2024-03-01T20:31:54.052  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.DescribeTable => 200
2024-03-01T20:31:54.169  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.DeleteTable => 200
2024-03-01T20:31:54.185  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.ListTables => 200
2024-03-01T20:31:54.193  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.ListTables => 200
2024-03-01T20:31:54.214  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.CreateTable => 200
2024-03-01T20:31:54.240  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.DescribeTable => 200
2024-03-01T20:31:54.434  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:54.454  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:54.468  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:54.485  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:54.499  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:54.513  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:54.526  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:54.540  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:54.554  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:54.567  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:54.581  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.GetItem => 200
2024-03-01T20:31:54.608  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.DeleteTable => 200
2024-03-01T20:31:54.615  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.ListTables => 200
2024-03-01T20:31:54.621  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.ListTables => 200
2024-03-01T20:31:54.638  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.CreateTable => 200
2024-03-01T20:31:54.645  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.DescribeTable => 200
2024-03-01T20:31:56.925  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:56.926  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:56.946  INFO --- [   asgi_gw_4] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:56.950  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:56.955  INFO --- [   asgi_gw_9] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:56.959  INFO --- [   asgi_gw_6] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:56.963  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:56.968  INFO --- [   asgi_gw_8] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:56.972  INFO --- [   asgi_gw_5] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:56.976  INFO --- [   asgi_gw_7] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:56.985  INFO --- [  asgi_gw_12] localstack.request.aws     : AWS dynamodb.GetItem => 200
2024-03-01T20:31:57.027  INFO --- [  asgi_gw_10] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.030  INFO --- [  asgi_gw_11] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.037  INFO --- [  asgi_gw_13] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.045  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.048  INFO --- [  asgi_gw_15] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.053  INFO --- [   asgi_gw_4] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.057  INFO --- [  asgi_gw_17] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.063  INFO --- [  asgi_gw_18] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.067  INFO --- [  asgi_gw_16] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.072  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.079  INFO --- [   asgi_gw_9] localstack.request.aws     : AWS dynamodb.GetItem => 200
2024-03-01T20:31:57.099  INFO --- [   asgi_gw_6] localstack.request.aws     : AWS dynamodb.DeleteItem => 200
2024-03-01T20:31:57.127  INFO --- [  asgi_gw_15] localstack.request.aws     : AWS dynamodb.GetItem => 200
2024-03-01T20:31:57.142  INFO --- [   asgi_gw_5] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.146  INFO --- [  asgi_gw_11] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.156  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.162  INFO --- [   asgi_gw_4] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.169  INFO --- [  asgi_gw_17] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.171 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
await app(scope, receive, send, sync_spawn, call_soon)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
await self.app(scope, receive, send)
File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
return await self.adapter(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 488, in __call__
return await self.handle_http(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 559, in handle_http
await response.close()
File "/opt/code/localstack/localstack/http/asgi.py", line 311, in close
await self.send({"type": "http.response.body", "body": b"", "more_body": False})
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
await self.send(EndBody(stream_id=self.stream_id))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
await self._send_h11_event(h11.EndOfMessage())
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
data = self.connection.send(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
data_list = self.send_with_data_passthrough(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
writer(event, data_list.append)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 67, in __call__
self.send_eom(event.headers, write)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 96, in send_eom
raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
2024-03-01T20:31:57.171 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
await app(scope, receive, send, sync_spawn, call_soon)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
await self.app(scope, receive, send)
File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
return await self.adapter(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 488, in __call__
return await self.handle_http(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 559, in handle_http
await response.close()
File "/opt/code/localstack/localstack/http/asgi.py", line 311, in close
await self.send({"type": "http.response.body", "body": b"", "more_body": False})
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
await self.send(EndBody(stream_id=self.stream_id))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
await self._send_h11_event(h11.EndOfMessage())
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
data = self.connection.send(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
data_list = self.send_with_data_passthrough(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
writer(event, data_list.append)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 67, in __call__
self.send_eom(event.headers, write)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 96, in send_eom
raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
2024-03-01T20:31:57.174  INFO --- [  asgi_gw_13] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.175 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
await app(scope, receive, send, sync_spawn, call_soon)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
await self.app(scope, receive, send)
File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
return await self.adapter(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 488, in __call__
return await self.handle_http(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 559, in handle_http
await response.close()
File "/opt/code/localstack/localstack/http/asgi.py", line 311, in close
await self.send({"type": "http.response.body", "body": b"", "more_body": False})
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
await self.send(EndBody(stream_id=self.stream_id))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
await self._send_h11_event(h11.EndOfMessage())
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
data = self.connection.send(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
data_list = self.send_with_data_passthrough(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
writer(event, data_list.append)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 67, in __call__
self.send_eom(event.headers, write)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 96, in send_eom
raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
2024-03-01T20:31:57.175 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
await app(scope, receive, send, sync_spawn, call_soon)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
await self.app(scope, receive, send)
File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
return await self.adapter(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 488, in __call__
return await self.handle_http(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 559, in handle_http
await response.close()
File "/opt/code/localstack/localstack/http/asgi.py", line 311, in close
await self.send({"type": "http.response.body", "body": b"", "more_body": False})
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
await self.send(EndBody(stream_id=self.stream_id))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
await self._send_h11_event(h11.EndOfMessage())
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
data = self.connection.send(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
data_list = self.send_with_data_passthrough(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
writer(event, data_list.append)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 67, in __call__
self.send_eom(event.headers, write)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 96, in send_eom
raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
2024-03-01T20:31:57.182  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.184 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
await app(scope, receive, send, sync_spawn, call_soon)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
await self.app(scope, receive, send)
File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
return await self.adapter(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 488, in __call__
return await self.handle_http(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 559, in handle_http
await response.close()
File "/opt/code/localstack/localstack/http/asgi.py", line 311, in close
await self.send({"type": "http.response.body", "body": b"", "more_body": False})
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
await self.send(EndBody(stream_id=self.stream_id))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
await self._send_h11_event(h11.EndOfMessage())
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
data = self.connection.send(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
data_list = self.send_with_data_passthrough(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
writer(event, data_list.append)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 67, in __call__
self.send_eom(event.headers, write)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 96, in send_eom
raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
2024-03-01T20:31:57.184 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
await app(scope, receive, send, sync_spawn, call_soon)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
await self.app(scope, receive, send)
File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
return await self.adapter(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 488, in __call__
return await self.handle_http(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 559, in handle_http
await response.close()
File "/opt/code/localstack/localstack/http/asgi.py", line 311, in close
await self.send({"type": "http.response.body", "body": b"", "more_body": False})
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
await self.send(EndBody(stream_id=self.stream_id))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
await self._send_h11_event(h11.EndOfMessage())
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
data = self.connection.send(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
data_list = self.send_with_data_passthrough(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
writer(event, data_list.append)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 67, in __call__
self.send_eom(event.headers, write)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 96, in send_eom
raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
2024-03-01T20:31:57.188  INFO --- [  asgi_gw_10] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.190 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
await app(scope, receive, send, sync_spawn, call_soon)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
await self.app(scope, receive, send)
File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
return await self.adapter(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 488, in __call__
return await self.handle_http(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 559, in handle_http
await response.close()
File "/opt/code/localstack/localstack/http/asgi.py", line 311, in close
await self.send({"type": "http.response.body", "body": b"", "more_body": False})
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
await self.send(EndBody(stream_id=self.stream_id))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
await self._send_h11_event(h11.EndOfMessage())
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
data = self.connection.send(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
data_list = self.send_with_data_passthrough(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
writer(event, data_list.append)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 67, in __call__
self.send_eom(event.headers, write)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 96, in send_eom
raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
2024-03-01T20:31:57.190 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
await app(scope, receive, send, sync_spawn, call_soon)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
await self.app(scope, receive, send)
File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
return await self.adapter(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 488, in __call__
return await self.handle_http(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 559, in handle_http
await response.close()
File "/opt/code/localstack/localstack/http/asgi.py", line 311, in close
await self.send({"type": "http.response.body", "body": b"", "more_body": False})
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
await self.send(EndBody(stream_id=self.stream_id))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
await self._send_h11_event(h11.EndOfMessage())
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
data = self.connection.send(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
data_list = self.send_with_data_passthrough(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
writer(event, data_list.append)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 67, in __call__
self.send_eom(event.headers, write)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 96, in send_eom
raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
2024-03-01T20:31:57.195  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.197 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
await app(scope, receive, send, sync_spawn, call_soon)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
await self.app(scope, receive, send)
File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
return await self.adapter(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 488, in __call__
return await self.handle_http(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 559, in handle_http
await response.close()
File "/opt/code/localstack/localstack/http/asgi.py", line 311, in close
await self.send({"type": "http.response.body", "body": b"", "more_body": False})
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
await self.send(EndBody(stream_id=self.stream_id))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
await self._send_h11_event(h11.EndOfMessage())
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
data = self.connection.send(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
data_list = self.send_with_data_passthrough(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
writer(event, data_list.append)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 67, in __call__
self.send_eom(event.headers, write)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 96, in send_eom
raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
2024-03-01T20:31:57.197 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
await app(scope, receive, send, sync_spawn, call_soon)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
await self.app(scope, receive, send)
File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
return await self.adapter(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 488, in __call__
return await self.handle_http(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 559, in handle_http
await response.close()
File "/opt/code/localstack/localstack/http/asgi.py", line 311, in close
await self.send({"type": "http.response.body", "body": b"", "more_body": False})
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
await self.send(EndBody(stream_id=self.stream_id))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
await self._send_h11_event(h11.EndOfMessage())
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
data = self.connection.send(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
data_list = self.send_with_data_passthrough(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
writer(event, data_list.append)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 67, in __call__
self.send_eom(event.headers, write)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 96, in send_eom
raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
2024-03-01T20:31:57.200  INFO --- [  asgi_gw_18] localstack.request.aws     : AWS dynamodb.PutItem => 200
2024-03-01T20:31:57.201 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
await app(scope, receive, send, sync_spawn, call_soon)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
await self.app(scope, receive, send)
File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
return await self.adapter(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 488, in __call__
return await self.handle_http(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 559, in handle_http
await response.close()
File "/opt/code/localstack/localstack/http/asgi.py", line 311, in close
await self.send({"type": "http.response.body", "body": b"", "more_body": False})
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
await self.send(EndBody(stream_id=self.stream_id))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
await self._send_h11_event(h11.EndOfMessage())
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
data = self.connection.send(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
data_list = self.send_with_data_passthrough(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
writer(event, data_list.append)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 67, in __call__
self.send_eom(event.headers, write)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 96, in send_eom
raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
2024-03-01T20:31:57.201 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
await app(scope, receive, send, sync_spawn, call_soon)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
await self.app(scope, receive, send)
File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
return await self.adapter(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 488, in __call__
return await self.handle_http(scope, receive, send)
File "/opt/code/localstack/localstack/http/asgi.py", line 559, in handle_http
await response.close()
File "/opt/code/localstack/localstack/http/asgi.py", line 311, in close
await self.send({"type": "http.response.body", "body": b"", "more_body": False})
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
await self.send(EndBody(stream_id=self.stream_id))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
await self._send_h11_event(h11.EndOfMessage())
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
data = self.connection.send(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
data_list = self.send_with_data_passthrough(event)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
writer(event, data_list.append)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 67, in __call__
self.send_eom(event.headers, write)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/h11/_writers.py", line 96, in send_eom
raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
