<?xml version="1.0" encoding="utf-8"?>
<TestRun id="1d766e46-dcc8-4156-a3b4-f9cc8a099c02" name="anna@cloudtest-win10 2023-01-23 04:51:33" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-23T04:51:33.2208127+00:00" queuing="2023-01-23T04:51:33.2208133+00:00" start="2023-01-23T04:49:52.7474012+00:00" finish="2023-01-23T04:51:33.2571819+00:00" />
  <TestSettings name="default" id="25b09f6f-a368-476e-9901-905367ce0de1">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-23_04_51_33" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="257e13f8-1367-4fce-b224-829e5db20e6e" testId="a54a19bb-f9f5-e5b0-e7e8-37cf937bc901" testName="Tester.AzureUtils.Lease.LeaseBasedQueueBalancerTests.LeaseBalancedQueueBalancer_SupportUnexpectedNodeFailureScenerio" computerName="cloudtest-win10" duration="00:01:07.5581204" startTime="2023-01-23T04:51:32.9107551+00:00" endTime="2023-01-23T04:51:32.9108028+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="257e13f8-1367-4fce-b224-829e5db20e6e" />
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.Lease.LeaseBasedQueueBalancerTests.LeaseBalancedQueueBalancer_SupportUnexpectedNodeFailureScenerio" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="a54a19bb-f9f5-e5b0-e7e8-37cf937bc901">
      <Execution id="257e13f8-1367-4fce-b224-829e5db20e6e" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.Lease.LeaseBasedQueueBalancerTests" name="LeaseBalancedQueueBalancer_SupportUnexpectedNodeFailureScenerio" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="a54a19bb-f9f5-e5b0-e7e8-37cf937bc901" executionId="257e13f8-1367-4fce-b224-829e5db20e6e" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.23]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.44]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.46]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:01:37.28]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-23T04:51:33.0775442+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>