<?xml version="1.0" encoding="utf-8"?>
<TestRun id="92de7b67-8dde-4e4c-9993-880e7ca0feca" name="anna@cloudtest-win10 2023-01-22 23:58:30" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-22T23:58:30.7377293+00:00" queuing="2023-01-22T23:58:30.7377299+00:00" start="2023-01-22T23:58:24.1984224+00:00" finish="2023-01-22T23:58:30.7780840+00:00" />
  <TestSettings name="default" id="34ff894f-f09c-4ae8-862c-2029fd94526b">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-22_23_58_30" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="e8b82e8b-2d3f-4506-9a3a-2cd51ac953c6" testId="e1f937ca-e18c-358d-8d22-1975310785f5" testName="Tester.AzureUtils.AzureTableDataManagerTests.AzureTableDataManager_UpdateTwoTableEntriesConditionallyAsync" computerName="cloudtest-win10" duration="00:00:01.6673419" startTime="2023-01-22T23:58:30.4368200+00:00" endTime="2023-01-22T23:58:30.4368646+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="e8b82e8b-2d3f-4506-9a3a-2cd51ac953c6">
      <Output>
        <ErrorInfo>
          <Message>Azure.RequestFailedException : The specified entity already exists.
RequestId:e85099c4-3002-0087-4ebd-2ed862000000
Time:2023-01-22T23:58:30.4344827Z&#xD;
Status: 409 (Conflict)&#xD;
ErrorCode: EntityAlreadyExists&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"EntityAlreadyExists","message":{"lang":"en-US","value":"The specified entity already exists.\nRequestId:e85099c4-3002-0087-4ebd-2ed862000000\nTime:2023-01-22T23:58:30.4344827Z"}}}&#xD;
&#xD;
Headers:&#xD;
Cache-Control: no-cache&#xD;
Server: Windows-Azure-Table/1.0,Microsoft-HTTPAPI/2.0&#xD;
x-ms-request-id: e85099c4-3002-0087-4ebd-2ed862000000&#xD;
x-ms-client-request-id: 2c23fa78-92ea-4de7-a7a6-a51aee44196a&#xD;
x-ms-version: REDACTED&#xD;
X-Content-Type-Options: REDACTED&#xD;
Preference-Applied: REDACTED&#xD;
Date: Sun, 22 Jan 2023 23:58:29 GMT&#xD;
Connection: keep-alive&#xD;
Content-Type: application/json; odata=minimalmetadata; streaming=true; charset=utf-8&#xD;
Content-Length: 203&#xD;
</Message>
          <StackTrace>   at Azure.Data.Tables.TableRestClient.InsertEntityAsync(String table, Nullable`1 timeout, Nullable`1 responsePreference, IDictionary`2 tableEntityProperties, QueryOptions queryOptions, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.AddEntityAsync[T](T entity, CancellationToken cancellationToken)&#xD;
   at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.CreateTableEntryAsync(T data) in C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs:line 171&#xD;
   at Tester.AzureUtils.AzureTableDataManagerTests.AzureTableDataManager_UpdateTwoTableEntriesConditionallyAsync() in C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureTableDataManagerTests.cs:line 288&#xD;
--- End of stack trace from previous location ---</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.AzureTableDataManagerTests.AzureTableDataManager_UpdateTwoTableEntriesConditionallyAsync" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="e1f937ca-e18c-358d-8d22-1975310785f5">
      <Execution id="e8b82e8b-2d3f-4506-9a3a-2cd51ac953c6" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.AzureTableDataManagerTests" name="AzureTableDataManager_UpdateTwoTableEntriesConditionallyAsync" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="e1f937ca-e18c-358d-8d22-1975310785f5" executionId="e8b82e8b-2d3f-4506-9a3a-2cd51ac953c6" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.27]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.49]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.50]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:03.25]       Azure.RequestFailedException : The specified entity already exists.
RequestId:e85099c4-3002-0087-4ebd-2ed862000000
Time:2023-01-22T23:58:30.4344827Z&#xD;
[xUnit.net 00:00:03.26]       Status: 409 (Conflict)&#xD;
[xUnit.net 00:00:03.26]       ErrorCode: EntityAlreadyExists&#xD;
[xUnit.net 00:00:03.26]       &#xD;
[xUnit.net 00:00:03.26]       Content:&#xD;
[xUnit.net 00:00:03.26]       {"odata.error":{"code":"EntityAlreadyExists","message":{"lang":"en-US","value":"The specified entity already exists.\nRequestId:e85099c4-3002-0087-4ebd-2ed862000000\nTime:2023-01-22T23:58:30.4344827Z"}}}&#xD;
[xUnit.net 00:00:03.26]       &#xD;
[xUnit.net 00:00:03.26]       Headers:&#xD;
[xUnit.net 00:00:03.26]       Cache-Control: no-cache&#xD;
[xUnit.net 00:00:03.26]       Server: Windows-Azure-Table/1.0,Microsoft-HTTPAPI/2.0&#xD;
[xUnit.net 00:00:03.26]       x-ms-request-id: e85099c4-3002-0087-4ebd-2ed862000000&#xD;
[xUnit.net 00:00:03.26]       x-ms-client-request-id: 2c23fa78-92ea-4de7-a7a6-a51aee44196a&#xD;
[xUnit.net 00:00:03.26]       x-ms-version: REDACTED&#xD;
[xUnit.net 00:00:03.26]       X-Content-Type-Options: REDACTED&#xD;
[xUnit.net 00:00:03.26]       Preference-Applied: REDACTED&#xD;
[xUnit.net 00:00:03.26]       Date: Sun, 22 Jan 2023 23:58:29 GMT&#xD;
[xUnit.net 00:00:03.26]       Connection: keep-alive&#xD;
[xUnit.net 00:00:03.26]       Content-Type: application/json; odata=minimalmetadata; streaming=true; charset=utf-8&#xD;
[xUnit.net 00:00:03.26]       Content-Length: 203&#xD;
[xUnit.net 00:00:03.26]       &#xD;
[xUnit.net 00:00:03.26]       Stack Trace:&#xD;
[xUnit.net 00:00:03.26]            at Azure.Data.Tables.TableRestClient.InsertEntityAsync(String table, Nullable`1 timeout, Nullable`1 responsePreference, IDictionary`2 tableEntityProperties, QueryOptions queryOptions, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:03.26]            at Azure.Data.Tables.TableClient.AddEntityAsync[T](T entity, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:03.26]         C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs(171,0): at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.CreateTableEntryAsync(T data)&#xD;
[xUnit.net 00:00:03.26]         C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureTableDataManagerTests.cs(288,0): at Tester.AzureUtils.AzureTableDataManagerTests.AzureTableDataManager_UpdateTwoTableEntriesConditionallyAsync()&#xD;
[xUnit.net 00:00:03.26]         --- End of stack trace from previous location ---&#xD;
[xUnit.net 00:00:03.29]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-22T23:58:30.4309570+00:00">
        <Text>[xUnit.net 00:00:03.25]     Tester.AzureUtils.AzureTableDataManagerTests.AzureTableDataManager_UpdateTwoTableEntriesConditionallyAsync [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-22T23:58:30.5911796+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>