<?xml version="1.0" encoding="utf-8"?>
<TestRun id="c47ace1b-84a0-43e8-8fa7-8352d10e4b70" name="anna@cloudtest-win10 2023-01-23 15:34:00" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-23T15:34:00.6497364+00:00" queuing="2023-01-23T15:34:00.6497370+00:00" start="2023-01-23T15:32:16.7278671+00:00" finish="2023-01-23T15:34:00.6874595+00:00" />
  <TestSettings name="default" id="1af2ddf6-9cbe-4d4d-a00c-efc53850871b">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-23_15_34_00" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="a103b28d-42a0-4a30-984e-05301109cff4" testId="a54a19bb-f9f5-e5b0-e7e8-37cf937bc901" testName="Tester.AzureUtils.Lease.LeaseBasedQueueBalancerTests.LeaseBalancedQueueBalancer_SupportUnexpectedNodeFailureScenerio" computerName="cloudtest-win10" duration="00:01:08.7917176" startTime="2023-01-23T15:34:00.3233473+00:00" endTime="2023-01-23T15:34:00.3233965+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="a103b28d-42a0-4a30-984e-05301109cff4" />
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.Lease.LeaseBasedQueueBalancerTests.LeaseBalancedQueueBalancer_SupportUnexpectedNodeFailureScenerio" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="a54a19bb-f9f5-e5b0-e7e8-37cf937bc901">
      <Execution id="a103b28d-42a0-4a30-984e-05301109cff4" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.Lease.LeaseBasedQueueBalancerTests" name="LeaseBalancedQueueBalancer_SupportUnexpectedNodeFailureScenerio" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="a54a19bb-f9f5-e5b0-e7e8-37cf937bc901" executionId="a103b28d-42a0-4a30-984e-05301109cff4" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.24]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.44]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.46]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:01:40.74]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-23T15:34:00.5012472+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>