<?xml version="1.0" encoding="utf-8"?>
<TestRun id="9c47d745-5c5c-41a5-b9d1-2064f3bc284f" name="anna@cloudtest-win10 2023-01-23 15:25:15" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-23T15:25:15.2262338+00:00" queuing="2023-01-23T15:25:15.2262345+00:00" start="2023-01-23T15:23:32.5076160+00:00" finish="2023-01-23T15:25:15.2615129+00:00" />
  <TestSettings name="default" id="36c6e8c3-7e33-47e1-8e32-a89d591c7c95">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-23_15_25_15" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="ebe2961b-cb21-4e40-9816-60fc2ade48e5" testId="a54a19bb-f9f5-e5b0-e7e8-37cf937bc901" testName="Tester.AzureUtils.Lease.LeaseBasedQueueBalancerTests.LeaseBalancedQueueBalancer_SupportUnexpectedNodeFailureScenerio" computerName="cloudtest-win10" duration="00:01:08.2960112" startTime="2023-01-23T15:25:14.9022127+00:00" endTime="2023-01-23T15:25:14.9022596+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="ebe2961b-cb21-4e40-9816-60fc2ade48e5" />
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.Lease.LeaseBasedQueueBalancerTests.LeaseBalancedQueueBalancer_SupportUnexpectedNodeFailureScenerio" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="a54a19bb-f9f5-e5b0-e7e8-37cf937bc901">
      <Execution id="ebe2961b-cb21-4e40-9816-60fc2ade48e5" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.Lease.LeaseBasedQueueBalancerTests" name="LeaseBalancedQueueBalancer_SupportUnexpectedNodeFailureScenerio" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="a54a19bb-f9f5-e5b0-e7e8-37cf937bc901" executionId="ebe2961b-cb21-4e40-9816-60fc2ade48e5" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.23]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.44]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.45]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:01:39.54]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-23T15:25:15.0819673+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>