<?xml version="1.0" encoding="utf-8"?>
<TestRun id="31197965-f023-4035-9bce-45e0d41a5de9" name="anna@cloudtest-win10 2023-01-23 15:32:14" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-23T15:32:14.5756855+00:00" queuing="2023-01-23T15:32:14.5756862+00:00" start="2023-01-23T15:30:30.9250996+00:00" finish="2023-01-23T15:32:14.6123427+00:00" />
  <TestSettings name="default" id="224dfaf4-c6b5-4673-81b0-c015babfa991">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-23_15_32_14" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="125e0018-588f-45b5-82f8-ef0b8d510e4f" testId="a54a19bb-f9f5-e5b0-e7e8-37cf937bc901" testName="Tester.AzureUtils.Lease.LeaseBasedQueueBalancerTests.LeaseBalancedQueueBalancer_SupportUnexpectedNodeFailureScenerio" computerName="cloudtest-win10" duration="00:01:08.4712127" startTime="2023-01-23T15:32:14.2594070+00:00" endTime="2023-01-23T15:32:14.2594538+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="125e0018-588f-45b5-82f8-ef0b8d510e4f" />
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.Lease.LeaseBasedQueueBalancerTests.LeaseBalancedQueueBalancer_SupportUnexpectedNodeFailureScenerio" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="a54a19bb-f9f5-e5b0-e7e8-37cf937bc901">
      <Execution id="125e0018-588f-45b5-82f8-ef0b8d510e4f" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.Lease.LeaseBasedQueueBalancerTests" name="LeaseBalancedQueueBalancer_SupportUnexpectedNodeFailureScenerio" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="a54a19bb-f9f5-e5b0-e7e8-37cf937bc901" executionId="125e0018-588f-45b5-82f8-ef0b8d510e4f" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.24]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.44]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.45]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:01:40.42]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-23T15:32:14.4323312+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>