<?xml version="1.0" encoding="utf-8"?>
<TestRun id="1432775b-e7b5-48fc-bff6-4daf222ea4c5" name="anna@cloudtest-win10 2023-01-22 23:13:49" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-22T23:13:49.3437191+00:00" queuing="2023-01-22T23:13:49.3437198+00:00" start="2023-01-22T23:13:42.7041901+00:00" finish="2023-01-22T23:13:49.3831502+00:00" />
  <TestSettings name="default" id="4175c6a9-e2db-407a-903a-865c44d805d4">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-22_23_13_49" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="930448b2-5291-4a0d-a6a1-910c5d556c97" testId="70490d52-ffd4-9caf-c9bb-f024ea7851e1" testName="Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_2" computerName="cloudtest-win10" duration="00:00:01.5836809" startTime="2023-01-22T23:13:49.0324855+00:00" endTime="2023-01-22T23:13:49.0325326+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="930448b2-5291-4a0d-a6a1-910c5d556c97">
      <Output>
        <ErrorInfo>
          <Message>Assert.Equal() Failure&#xD;
Expected: 10&#xD;
Actual:   11</Message>
          <StackTrace>   at Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_2() in C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureQueueDataManagerTests.cs:line 95&#xD;
--- End of stack trace from previous location ---</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_2" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="70490d52-ffd4-9caf-c9bb-f024ea7851e1">
      <Execution id="930448b2-5291-4a0d-a6a1-910c5d556c97" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.AzureQueueDataManagerTests" name="AQ_Standalone_2" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="70490d52-ffd4-9caf-c9bb-f024ea7851e1" executionId="930448b2-5291-4a0d-a6a1-910c5d556c97" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.27]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.49]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.50]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:03.36]       Assert.Equal() Failure&#xD;
[xUnit.net 00:00:03.36]       Expected: 10&#xD;
[xUnit.net 00:00:03.36]       Actual:   11&#xD;
[xUnit.net 00:00:03.36]       Stack Trace:&#xD;
[xUnit.net 00:00:03.36]         C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureQueueDataManagerTests.cs(95,0): at Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_2()&#xD;
[xUnit.net 00:00:03.36]         --- End of stack trace from previous location ---&#xD;
[xUnit.net 00:00:03.40]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-22T23:13:49.0275222+00:00">
        <Text>[xUnit.net 00:00:03.36]     Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_2 [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-22T23:13:49.1951592+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>