<?xml version="1.0" encoding="utf-8"?>
<TestRun id="e920d107-6acd-4bd3-b260-df970b12c877" name="anna@cloudtest-win10 2023-01-24 01:50:36" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-24T01:50:36.2076618+00:00" queuing="2023-01-24T01:50:36.2076624+00:00" start="2023-01-24T01:50:29.2420873+00:00" finish="2023-01-24T01:50:36.2514860+00:00" />
  <TestSettings name="default" id="25743054-e251-4147-b5dd-0d5242334a07">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-24_01_50_36" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="156f5926-8b3f-41ac-ab7b-aa565e5cf205" testId="d8f5a3dc-7553-7c5e-0a7c-ee51dead7147" testName="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_FindAllGatewayProxyEndpoints" computerName="cloudtest-win10" duration="00:00:02.0750535" startTime="2023-01-24T01:50:35.9054764+00:00" endTime="2023-01-24T01:50:35.9055276+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="156f5926-8b3f-41ac-ab7b-aa565e5cf205">
      <Output>
        <StdOut>ClusterId=test-f031df9d-2547-44cc-9696-08e67240f163 Generation=33529833&#xD;
Initializing SiloInstanceManager&#xD;
MyEntry=OrleansSilo [ Deployment=test-f031df9d-2547-44cc-9696-08e67240f163 LocalEndpoint=127.0.0.1 LocalPort=0 Generation=33529833 Host=127.0.0.1 Status= ProxyPort=30000 RoleName=MyRole SiloName=MyInstance UpgradeZone=0 FaultZone=0 StartTime=2023-01-24 01:50:34.536 GMT IAmAliveTime=]&#xD;
TestCleanup Timeout=00:01:00</StdOut>
        <ErrorInfo>
          <Message>System.AggregateException : One or more errors occurred. (The specified resource does not exist.
RequestId:825ff3ac-b002-0020-4d96-2f30a0000000
Time:2023-01-24T01:50:35.8730903Z&#xD;
Status: 404 (Not Found)&#xD;
ErrorCode: ResourceNotFound&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:825ff3ac-b002-0020-4d96-2f30a0000000\nTime:2023-01-24T01:50:35.8730903Z"}}}&#xD;
&#xD;
Headers:&#xD;
X-Content-Type-Options: REDACTED&#xD;
Cache-Control: no-cache&#xD;
DataServiceVersion: 3.0;&#xD;
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
)&#xD;
---- Azure.Data.Tables.TableTransactionFailedException : The specified resource does not exist.
RequestId:825ff3ac-b002-0020-4d96-2f30a0000000
Time:2023-01-24T01:50:35.8730903Z&#xD;
Status: 404 (Not Found)&#xD;
ErrorCode: ResourceNotFound&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:825ff3ac-b002-0020-4d96-2f30a0000000\nTime:2023-01-24T01:50:35.8730903Z"}}}&#xD;
&#xD;
Headers:&#xD;
X-Content-Type-Options: REDACTED&#xD;
Cache-Control: no-cache&#xD;
DataServiceVersion: 3.0;&#xD;
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
</Message>
          <StackTrace>   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#xD;
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#xD;
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)&#xD;
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)&#xD;
   at Orleans.Internal.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout) in C:\Users\anna\orleans\src\Orleans.Core\Async\TaskExtensions.cs:line 49&#xD;
   at Tester.AzureUtils.SiloInstanceTableManagerTests.Dispose() in C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\SiloInstanceTableManagerTests.cs:line 70&#xD;
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs:line 79&#xD;
----- Inner Stack Trace -----&#xD;
   at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)&#xD;
   at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.DeleteTableEntriesAsync(List`1 collection) in C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs:line 483&#xD;
   at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteEntriesBatch(List`1 entriesList) in C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs:line 197&#xD;
   at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteTableEntries(String clusterId) in C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs:line 177</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_FindAllGatewayProxyEndpoints" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="d8f5a3dc-7553-7c5e-0a7c-ee51dead7147">
      <Execution id="156f5926-8b3f-41ac-ab7b-aa565e5cf205" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.SiloInstanceTableManagerTests" name="SiloInstanceTable_FindAllGatewayProxyEndpoints" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="d8f5a3dc-7553-7c5e-0a7c-ee51dead7147" executionId="156f5926-8b3f-41ac-ab7b-aa565e5cf205" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.27]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.48]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.49]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:03.66]       System.AggregateException : One or more errors occurred. (The specified resource does not exist.
RequestId:825ff3ac-b002-0020-4d96-2f30a0000000
Time:2023-01-24T01:50:35.8730903Z&#xD;
[xUnit.net 00:00:03.66]       Status: 404 (Not Found)&#xD;
[xUnit.net 00:00:03.66]       ErrorCode: ResourceNotFound&#xD;
[xUnit.net 00:00:03.67]       &#xD;
[xUnit.net 00:00:03.67]       Content:&#xD;
[xUnit.net 00:00:03.67]       {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:825ff3ac-b002-0020-4d96-2f30a0000000\nTime:2023-01-24T01:50:35.8730903Z"}}}&#xD;
[xUnit.net 00:00:03.67]       &#xD;
[xUnit.net 00:00:03.67]       Headers:&#xD;
[xUnit.net 00:00:03.67]       X-Content-Type-Options: REDACTED&#xD;
[xUnit.net 00:00:03.67]       Cache-Control: no-cache&#xD;
[xUnit.net 00:00:03.67]       DataServiceVersion: 3.0;&#xD;
[xUnit.net 00:00:03.67]       Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
[xUnit.net 00:00:03.67]       )&#xD;
[xUnit.net 00:00:03.67]       ---- Azure.Data.Tables.TableTransactionFailedException : The specified resource does not exist.
RequestId:825ff3ac-b002-0020-4d96-2f30a0000000
Time:2023-01-24T01:50:35.8730903Z&#xD;
[xUnit.net 00:00:03.67]       Status: 404 (Not Found)&#xD;
[xUnit.net 00:00:03.67]       ErrorCode: ResourceNotFound&#xD;
[xUnit.net 00:00:03.67]       &#xD;
[xUnit.net 00:00:03.67]       Content:&#xD;
[xUnit.net 00:00:03.67]       {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:825ff3ac-b002-0020-4d96-2f30a0000000\nTime:2023-01-24T01:50:35.8730903Z"}}}&#xD;
[xUnit.net 00:00:03.67]       &#xD;
[xUnit.net 00:00:03.67]       Headers:&#xD;
[xUnit.net 00:00:03.67]       X-Content-Type-Options: REDACTED&#xD;
[xUnit.net 00:00:03.67]       Cache-Control: no-cache&#xD;
[xUnit.net 00:00:03.67]       DataServiceVersion: 3.0;&#xD;
[xUnit.net 00:00:03.67]       Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
[xUnit.net 00:00:03.67]       &#xD;
[xUnit.net 00:00:03.67]       Stack Trace:&#xD;
[xUnit.net 00:00:03.67]            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#xD;
[xUnit.net 00:00:03.67]            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:03.67]            at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:03.67]            at System.Threading.Tasks.Task.Wait(TimeSpan timeout)&#xD;
[xUnit.net 00:00:03.67]         C:\Users\anna\orleans\src\Orleans.Core\Async\TaskExtensions.cs(49,0): at Orleans.Internal.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)&#xD;
[xUnit.net 00:00:03.67]         C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\SiloInstanceTableManagerTests.cs(70,0): at Tester.AzureUtils.SiloInstanceTableManagerTests.Dispose()&#xD;
[xUnit.net 00:00:03.67]         /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs(79,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)&#xD;
[xUnit.net 00:00:03.67]         ----- Inner Stack Trace -----&#xD;
[xUnit.net 00:00:03.67]            at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:03.67]            at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:03.67]            at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:03.67]         C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs(483,0): at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.DeleteTableEntriesAsync(List`1 collection)&#xD;
[xUnit.net 00:00:03.67]         C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs(197,0): at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteEntriesBatch(List`1 entriesList)&#xD;
[xUnit.net 00:00:03.67]         C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs(177,0): at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteTableEntries(String clusterId)&#xD;
[xUnit.net 00:00:03.67]       Output:&#xD;
[xUnit.net 00:00:03.67]         ClusterId=test-f031df9d-2547-44cc-9696-08e67240f163 Generation=33529833&#xD;
[xUnit.net 00:00:03.67]         Initializing SiloInstanceManager&#xD;
[xUnit.net 00:00:03.67]         MyEntry=OrleansSilo [ Deployment=test-f031df9d-2547-44cc-9696-08e67240f163 LocalEndpoint=127.0.0.1 LocalPort=0 Generation=33529833 Host=127.0.0.1 Status= ProxyPort=30000 RoleName=MyRole SiloName=MyInstance UpgradeZone=0 FaultZone=0 StartTime=2023-01-24 01:50:34.536 GMT IAmAliveTime=]&#xD;
[xUnit.net 00:00:03.67]         TestCleanup Timeout=00:01:00&#xD;
[xUnit.net 00:00:03.70]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-24T01:50:35.8980987+00:00">
        <Text>[xUnit.net 00:00:03.66]     Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_FindAllGatewayProxyEndpoints [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-24T01:50:36.0604302+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>