<?xml version="1.0" encoding="utf-8"?>
<TestRun id="29039026-1561-4c2a-a3f8-10ca08a4a994" name="anna@cloudtest-win10 2023-01-22 19:01:02" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-22T19:01:02.5892607+00:00" queuing="2023-01-22T19:01:02.5892612+00:00" start="2023-01-22T19:00:55.0902428+00:00" finish="2023-01-22T19:01:02.6308513+00:00" />
  <TestSettings name="default" id="fe67559f-a72a-48ec-b6e6-27adefc0232d">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-22_19_01_02" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="4008897b-df90-4dca-8c07-6ddf8a08c6c9" testId="0fc7afa1-bccc-bd57-5ca0-475359ca85dd" testName="Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_ReadAll_EmptyTable" computerName="cloudtest-win10" duration="00:00:01.6148130" startTime="2023-01-22T19:01:02.2696546+00:00" endTime="2023-01-22T19:01:02.2696994+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="4008897b-df90-4dca-8c07-6ddf8a08c6c9">
      <Output>
        <ErrorInfo>
          <Message>System.AggregateException : One or more errors occurred. (0:The specified resource does not exist.
RequestId:818546ba-3dd0-4b23-9dc1-e88e91ccc94a
Time:2023-01-22T19:01:02.201Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.&#xD;
Status: 404 (Not Found)&#xD;
ErrorCode: ResourceNotFound&#xD;
&#xD;
Additional Information:&#xD;
FailedEntity: 0&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"0:The specified resource does not exist.\nRequestId:818546ba-3dd0-4b23-9dc1-e88e91ccc94a\nTime:2023-01-22T19:01:02.201Z"}}}&#xD;
&#xD;
Headers:&#xD;
Content-ID: REDACTED&#xD;
DataServiceVersion: 3.0;&#xD;
Content-Type: application/json;odata=minimalmetadata;charset=utf-8&#xD;
)&#xD;
---- Azure.Data.Tables.TableTransactionFailedException : 0:The specified resource does not exist.
RequestId:818546ba-3dd0-4b23-9dc1-e88e91ccc94a
Time:2023-01-22T19:01:02.201Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.&#xD;
Status: 404 (Not Found)&#xD;
ErrorCode: ResourceNotFound&#xD;
&#xD;
Additional Information:&#xD;
FailedEntity: 0&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"0:The specified resource does not exist.\nRequestId:818546ba-3dd0-4b23-9dc1-e88e91ccc94a\nTime:2023-01-22T19:01:02.201Z"}}}&#xD;
&#xD;
Headers:&#xD;
Content-ID: REDACTED&#xD;
DataServiceVersion: 3.0;&#xD;
Content-Type: application/json;odata=minimalmetadata;charset=utf-8&#xD;
</Message>
          <StackTrace>   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#xD;
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#xD;
   at System.Threading.Tasks.Task.Wait()&#xD;
   at UnitTests.MembershipTests.MembershipTableTestsBase.Dispose() in C:\Users\anna\orleans\test\TesterInternal\MembershipTests\MembershipTableTestsBase.cs:line 85&#xD;
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs:line 79&#xD;
----- Inner Stack Trace -----&#xD;
   at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)&#xD;
   at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.DeleteTableEntriesAsync(List`1 collection) in C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs:line 483&#xD;
   at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteEntriesBatch(List`1 entriesList) in C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs:line 197&#xD;
   at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteTableEntries(String clusterId) in C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs:line 177</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_ReadAll_EmptyTable" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="0fc7afa1-bccc-bd57-5ca0-475359ca85dd">
      <Execution id="4008897b-df90-4dca-8c07-6ddf8a08c6c9" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.AzureMembershipTableTests" name="MembershipTable_Azure_ReadAll_EmptyTable" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="0fc7afa1-bccc-bd57-5ca0-475359ca85dd" executionId="4008897b-df90-4dca-8c07-6ddf8a08c6c9" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.29]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.50]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.51]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:04.19]       System.AggregateException : One or more errors occurred. (0:The specified resource does not exist.
RequestId:818546ba-3dd0-4b23-9dc1-e88e91ccc94a
Time:2023-01-22T19:01:02.201Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.&#xD;
[xUnit.net 00:00:04.19]       Status: 404 (Not Found)&#xD;
[xUnit.net 00:00:04.19]       ErrorCode: ResourceNotFound&#xD;
[xUnit.net 00:00:04.19]       &#xD;
[xUnit.net 00:00:04.19]       Additional Information:&#xD;
[xUnit.net 00:00:04.19]       FailedEntity: 0&#xD;
[xUnit.net 00:00:04.19]       &#xD;
[xUnit.net 00:00:04.19]       Content:&#xD;
[xUnit.net 00:00:04.19]       {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"0:The specified resource does not exist.\nRequestId:818546ba-3dd0-4b23-9dc1-e88e91ccc94a\nTime:2023-01-22T19:01:02.201Z"}}}&#xD;
[xUnit.net 00:00:04.19]       &#xD;
[xUnit.net 00:00:04.19]       Headers:&#xD;
[xUnit.net 00:00:04.19]       Content-ID: REDACTED&#xD;
[xUnit.net 00:00:04.19]       DataServiceVersion: 3.0;&#xD;
[xUnit.net 00:00:04.19]       Content-Type: application/json;odata=minimalmetadata;charset=utf-8&#xD;
[xUnit.net 00:00:04.19]       )&#xD;
[xUnit.net 00:00:04.19]       ---- Azure.Data.Tables.TableTransactionFailedException : 0:The specified resource does not exist.
RequestId:818546ba-3dd0-4b23-9dc1-e88e91ccc94a
Time:2023-01-22T19:01:02.201Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.&#xD;
[xUnit.net 00:00:04.19]       Status: 404 (Not Found)&#xD;
[xUnit.net 00:00:04.19]       ErrorCode: ResourceNotFound&#xD;
[xUnit.net 00:00:04.19]       &#xD;
[xUnit.net 00:00:04.19]       Additional Information:&#xD;
[xUnit.net 00:00:04.19]       FailedEntity: 0&#xD;
[xUnit.net 00:00:04.19]       &#xD;
[xUnit.net 00:00:04.19]       Content:&#xD;
[xUnit.net 00:00:04.19]       {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"0:The specified resource does not exist.\nRequestId:818546ba-3dd0-4b23-9dc1-e88e91ccc94a\nTime:2023-01-22T19:01:02.201Z"}}}&#xD;
[xUnit.net 00:00:04.19]       &#xD;
[xUnit.net 00:00:04.19]       Headers:&#xD;
[xUnit.net 00:00:04.19]       Content-ID: REDACTED&#xD;
[xUnit.net 00:00:04.19]       DataServiceVersion: 3.0;&#xD;
[xUnit.net 00:00:04.19]       Content-Type: application/json;odata=minimalmetadata;charset=utf-8&#xD;
[xUnit.net 00:00:04.19]       &#xD;
[xUnit.net 00:00:04.19]       Stack Trace:&#xD;
[xUnit.net 00:00:04.19]            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#xD;
[xUnit.net 00:00:04.19]            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:04.19]            at System.Threading.Tasks.Task.Wait()&#xD;
[xUnit.net 00:00:04.19]         C:\Users\anna\orleans\test\TesterInternal\MembershipTests\MembershipTableTestsBase.cs(85,0): at UnitTests.MembershipTests.MembershipTableTestsBase.Dispose()&#xD;
[xUnit.net 00:00:04.19]         /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs(79,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)&#xD;
[xUnit.net 00:00:04.19]         ----- Inner Stack Trace -----&#xD;
[xUnit.net 00:00:04.19]            at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:04.19]            at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:04.19]            at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:04.19]         C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs(483,0): at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.DeleteTableEntriesAsync(List`1 collection)&#xD;
[xUnit.net 00:00:04.19]         C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs(197,0): at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteEntriesBatch(List`1 entriesList)&#xD;
[xUnit.net 00:00:04.19]         C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs(177,0): at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteTableEntries(String clusterId)&#xD;
[xUnit.net 00:00:04.23]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-22T19:01:02.2635282+00:00">
        <Text>[xUnit.net 00:00:04.19]     Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_ReadAll_EmptyTable [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-22T19:01:02.4422741+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>